spring:
  datasource:
    url: jdbc:mysql://39.98.7.208:13306/groovy_demo?autoReconnect=true&useUnicode=true&serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: groovy_demo
    password: GroovyDemo_123
    data: classpath:/sql/init-mysql.sql
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace